# Generated by Django 3.1.4 on 2020-12-06 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(max_length=120, verbose_name='Wallet ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Updated')),
                ('amount', models.FloatField(default=100.0)),
                ('currency', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(max_length=120, verbose_name='Wallet ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(verbose_name='Date Updated')),
                ('address', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet_API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(max_length=120, verbose_name='Wallet ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Updated')),
                ('api_key', models.CharField(max_length=120)),
                ('api_pin', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet_Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(max_length=120, verbose_name='Wallet ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Updated')),
                ('private_key', models.CharField(max_length=120)),
                ('public_key', models.CharField(max_length=120)),
                ('private_key_wif', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet_Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id_from', models.CharField(max_length=120, verbose_name='Wallet ID')),
                ('wallet_id_to', models.CharField(default=None, max_length=120, verbose_name='Wallet ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Updated')),
                ('transaction_id', models.CharField(max_length=120)),
                ('transaction_amount', models.FloatField()),
                ('transaction_currency', models.CharField(max_length=20)),
                ('commission_rate', models.FloatField(default=1.5)),
                ('commission', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(max_length=120, verbose_name='Wallet ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Created')),
                ('email', models.CharField(max_length=120)),
                ('wallet_account', models.ManyToManyField(to='pages.Wallet_Account')),
                ('wallet_address', models.ManyToManyField(to='pages.Wallet_Address')),
                ('wallet_api', models.ManyToManyField(to='pages.Wallet_API')),
                ('wallet_keys', models.ManyToManyField(to='pages.Wallet_Keys')),
            ],
        ),
    ]
